#!/usr/bin/env python3
"""wl: SQLite-backed work log. work_log.md is a generated export; the DB is queried."""
import argparse
import os
import re
import sqlite3
import sys
import tempfile
from datetime import datetime
from pathlib import Path
from typing import NamedTuple

TYPES = ("ticket", "pr", "idea", "decision", "blocker", "note")
# Project slugs are managed at runtime (`wl slug add/rm/ls`) and stored in the DB,
# not in this file. `known_slugs(conn)` returns them in display order.


class Entry(NamedTuple):
    ts: str    # ISO local 'YYYY-MM-DDTHH:MM:SS'; day = ts[:10]
    slug: str
    type: str
    refs: str  # comma-joined keys, '' if none
    body: str


_HHMM = re.compile(r"\d{2}:\d{2}")
_ISO_MIN = re.compile(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}")


def resolve_at(at, now=None):
    """None -> now; 'HH:MM' -> today at that time; 'YYYY-MM-DDTHH:MM' -> exact. Else ValueError.

    The regex checks the 2-digit shape; strptime then rejects impossible values
    (99:99, hour 24, month 13, ...) so garbage never reaches the timestamp column.
    """
    if now is None:
        now = datetime.now()
    if at is None:
        return now.strftime("%Y-%m-%dT%H:%M:%S")
    try:
        if _HHMM.fullmatch(at):
            datetime.strptime(at, "%H:%M")
            return now.strftime("%Y-%m-%d") + f"T{at}:00"
        if _ISO_MIN.fullmatch(at):
            datetime.strptime(at, "%Y-%m-%dT%H:%M")
            return at + ":00"
    except ValueError:
        pass  # shape matched but the value is impossible; fall through to one error
    raise ValueError(f"bad --at {at!r}; want HH:MM or YYYY-MM-DDTHH:MM")


def normalize_refs(s):
    """'PROJ-1, PROJ-2' -> 'PROJ-1,PROJ-2'; empty/None -> ''."""
    if not s:
        return ""
    return ",".join(p.strip() for p in s.split(",") if p.strip())


_DAY_RE = re.compile(r"^## (\d{4}-\d{2}-\d{2})\s*$")
_SLUG_RE = re.compile(r"^### (\S+)\s*$")
# body is non-greedy so the optional trailing refs suffix is not swallowed.
# ponytail: a body literally ending in "(refs: ...)" would mis-parse; no real entry does this.
_ENTRY_RE = re.compile(r"^- (\d{2}:\d{2}) \[(\w+)\] (.*?)(?:\s*\(refs:\s*(.*?)\))?\s*$")


def parse_markdown(text):
    """Parse a rendered work_log.md back into Entry rows. Header and pre-day lines ignored."""
    entries, day, slug = [], None, None
    for line in text.splitlines():
        m = _DAY_RE.match(line)
        if m:
            day, slug = m.group(1), None
            continue
        m = _SLUG_RE.match(line)
        if m:
            slug = m.group(1)
            continue
        m = _ENTRY_RE.match(line)
        if m and day and slug:
            hhmm, typ, body, refs = m.groups()
            refs = "" if not refs or refs.strip().lower() == "none" else normalize_refs(refs)
            entries.append(Entry(f"{day}T{hhmm}:00", slug, typ, refs, body.rstrip()))
    return entries


HEADER_BLOCK = (
    "# Work Log\n\n"
    "Generated by `wl` from work_log.db. Do not hand-edit; use `wl add`. Newest day first."
)


def slug_sort_key(slug, order):
    """Registered slugs in `order` first, then unregistered slugs alphabetically."""
    return (order.index(slug), "") if slug in order else (len(order), slug)


def render_day(day, entries, order):
    """One '## day' section: slug groups in display order, entries time-sorted. No file header."""
    lines = [f"## {day}", ""]
    for slug in sorted({e.slug for e in entries}, key=lambda s: slug_sort_key(s, order)):
        lines.append(f"### {slug}")
        for e in sorted((x for x in entries if x.slug == slug), key=lambda x: x.ts):
            refs = e.refs.replace(",", ", ") if e.refs else "none"
            lines.append(f"- {e.ts[11:16]} [{e.type}] {e.body} (refs: {refs})")
        lines.append("")  # blank line after each slug block
    return "\n".join(lines).rstrip()


def render_days(entries, order):
    """Group entries by day and render each as a '## day' section, newest day first."""
    by_day = {}
    for e in entries:
        by_day.setdefault(e.ts[:10], []).append(e)
    return "\n\n".join(render_day(d, by_day[d], order) for d in sorted(by_day, reverse=True))


def render_markdown(entries, order):
    """Full work_log.md: header + every day newest-first + trailing newline."""
    body = render_days(entries, order)
    return f"{HEADER_BLOCK}\n\n{body}\n" if body else f"{HEADER_BLOCK}\n"


_SCHEMA = """
CREATE TABLE IF NOT EXISTS entries(
  id   INTEGER PRIMARY KEY,
  ts   TEXT NOT NULL,
  slug TEXT NOT NULL,
  type TEXT NOT NULL,
  refs TEXT NOT NULL DEFAULT '',
  body TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_entries_ts ON entries(ts);
CREATE TABLE IF NOT EXISTS slugs(
  name TEXT PRIMARY KEY,
  pos  INTEGER NOT NULL   -- display order, ascending
);
"""


def root():
    env = os.environ.get("WORKLOG_ROOT")
    return Path(env) if env else Path(__file__).resolve().parent.parent


def md_path():
    return root() / "work_log.md"


def db_path():
    return root() / "work_log.db"


def _import_into(conn):
    """Rebuild the entries table from work_log.md (source of record)."""
    conn.execute("DELETE FROM entries")
    md = md_path()
    if md.exists():
        rows = [(e.ts, e.slug, e.type, e.refs, e.body) for e in parse_markdown(md.read_text())]
        conn.executemany(
            "INSERT INTO entries(ts,slug,type,refs,body) VALUES(?,?,?,?,?)", rows
        )
    conn.commit()


def connect():
    """Open the DB, ensure schema, and re-import the markdown if it is newer (or DB missing)."""
    db = db_path()
    stale = (not db.exists()) or (
        md_path().exists() and md_path().stat().st_mtime > db.stat().st_mtime
    )
    conn = sqlite3.connect(str(db))
    conn.execute("PRAGMA busy_timeout = 5000")
    conn.executescript(_SCHEMA)
    # ponytail: slugs live in the DB, not work_log.md, so they are machine-local
    # tooling config, not portable log content. A from-scratch `wl import` reseeds
    # to just 'general'. Add a slug export to the markdown only if that ever bites.
    if not conn.execute("SELECT 1 FROM slugs LIMIT 1").fetchone():
        conn.execute("INSERT INTO slugs(name, pos) VALUES('general', 0)")
        conn.commit()
    if stale:
        _import_into(conn)
    return conn


def _all_entries(conn):
    rows = conn.execute("SELECT ts,slug,type,refs,body FROM entries").fetchall()
    return [Entry(*r) for r in rows]


def known_slugs(conn):
    """Registered slug names in display (pos) order."""
    return [r[0] for r in conn.execute("SELECT name FROM slugs ORDER BY pos")]


def write_md(conn):
    """Render all entries and atomically replace work_log.md."""
    text = render_markdown(_all_entries(conn), known_slugs(conn))
    target = md_path()
    fd, tmp = tempfile.mkstemp(dir=str(target.parent), suffix=".tmp")
    with os.fdopen(fd, "w") as f:
        f.write(text)
    os.replace(tmp, str(target))


def cmd_add(args):
    if args.type not in TYPES:
        sys.exit(f"error: bad --type {args.type!r}; valid: {', '.join(TYPES)}")
    try:
        ts = resolve_at(args.at)
    except ValueError as e:
        sys.exit(f"error: {e}")
    refs = normalize_refs(args.ref)
    body = args.body.replace("\n", " ").strip()
    conn = connect()
    if args.slug not in known_slugs(conn):
        print(f"warning: unknown slug {args.slug!r} "
              f"(register it with `wl slug add {args.slug}`?)", file=sys.stderr)
    conn.execute(
        "INSERT INTO entries(ts,slug,type,refs,body) VALUES(?,?,?,?,?)",
        (ts, args.slug, args.type, refs, body),
    )
    conn.commit()
    write_md(conn)
    conn.close()
    refs_disp = refs.replace(",", ", ") if refs else "none"
    print(f"- {ts[11:16]} [{args.type}] {body} (refs: {refs_disp})")


def cmd_report(args):
    conn = connect()
    order = known_slugs(conn)
    entries = _all_entries(conn)
    conn.close()
    # Range mode (--since/--until) takes precedence over --day, so a roundup for a
    # standup or bi-weekly meeting is one command. Date strings are YYYY-MM-DD, which
    # compares correctly as plain strings; open-ended bounds use lexical sentinels.
    if args.since or args.until:
        lo, hi = args.since or "0000-00-00", args.until or "9999-99-99"
        sel = [e for e in entries if lo <= e.ts[:10] <= hi]
        label = f"{lo}..{hi}"
    else:
        day = datetime.now().strftime("%Y-%m-%d") if args.day == "today" else args.day
        sel = [e for e in entries if e.ts[:10] == day]
        label = day
    if not sel:
        print(f"(no entries for {label})")
        return
    print(render_days(sel, order))


def cmd_log(args):
    conn = connect()
    entries = _all_entries(conn)
    conn.close()

    def keep(e):
        if args.slug and e.slug != args.slug:
            return False
        if args.type and e.type != args.type:
            return False
        if args.ref and args.ref not in e.refs.split(","):
            return False
        if args.since and e.ts[:10] < args.since:
            return False
        if args.until and e.ts[:10] > args.until:
            return False
        return True

    hits = sorted((e for e in entries if keep(e)), key=lambda x: x.ts, reverse=True)
    for e in hits:
        refs = e.refs.replace(",", ", ") if e.refs else "none"
        print(f"{e.ts[:10]} {e.ts[11:16]} [{e.slug}] [{e.type}] {e.body} (refs: {refs})")


def cmd_render(args):
    conn = connect()
    write_md(conn)
    conn.close()
    print(f"rendered {md_path()}")


def cmd_import(args):
    conn = connect()
    _import_into(conn)  # force a rebuild even if connect() considered the DB fresh
    n = conn.execute("SELECT count(*) FROM entries").fetchone()[0]
    conn.close()
    print(f"imported {md_path()} -> {db_path()} ({n} entries)")


def cmd_slug(args):
    conn = connect()
    if args.action == "ls":
        for name in known_slugs(conn):
            print(name)
    elif args.action == "add":
        if not args.name:
            conn.close()
            sys.exit("error: `slug add` needs a name")
        # pos = one past the current max, so new slugs append to the display order.
        cur = conn.execute(
            "INSERT OR IGNORE INTO slugs(name, pos) "
            "VALUES(?, (SELECT COALESCE(MAX(pos), -1) + 1 FROM slugs))",
            (args.name,),
        )
        conn.commit()
        print(f"added slug {args.name!r}" if cur.rowcount
              else f"slug {args.name!r} already registered")
    elif args.action == "rm":
        if not args.name:
            conn.close()
            sys.exit("error: `slug rm` needs a name")
        cur = conn.execute("DELETE FROM slugs WHERE name = ?", (args.name,))
        conn.commit()
        if not cur.rowcount:
            print(f"slug {args.name!r} was not registered")
        else:
            n = conn.execute("SELECT count(*) FROM entries WHERE slug = ?",
                             (args.name,)).fetchone()[0]
            note = f" ({n} existing entries will now sort as unknown)" if n else ""
            print(f"removed slug {args.name!r}{note}")
    conn.close()


def main(argv=None):
    p = argparse.ArgumentParser(prog="wl", description="SQLite-backed work log.")
    sub = p.add_subparsers(dest="cmd", required=True)

    a = sub.add_parser("add", help="add an entry and re-render work_log.md")
    a.add_argument("--slug", required=True)
    a.add_argument("--type", required=True)
    a.add_argument("--ref", default="")
    a.add_argument("--at", help="HH:MM (today) or YYYY-MM-DDTHH:MM; default now")
    a.add_argument("body")
    a.set_defaults(fn=cmd_add)

    r = sub.add_parser("report", help="print one day (or a --since/--until range) as markdown")
    r.add_argument("--day", default="today")
    r.add_argument("--since", help="range start YYYY-MM-DD; groups every day in range")
    r.add_argument("--until", help="range end YYYY-MM-DD, inclusive")
    r.set_defaults(fn=cmd_report)

    g = sub.add_parser("log", help="filtered list across all history")
    g.add_argument("--slug")
    g.add_argument("--type")
    g.add_argument("--ref")
    g.add_argument("--since")
    g.add_argument("--until")
    g.set_defaults(fn=cmd_log)

    rn = sub.add_parser("render", help="regenerate work_log.md from the DB")
    rn.set_defaults(fn=cmd_render)

    im = sub.add_parser("import", help="rebuild the DB from work_log.md")
    im.set_defaults(fn=cmd_import)

    sl = sub.add_parser("slug", help="manage project slugs (ls/add/rm)")
    sl.add_argument("action", choices=("ls", "add", "rm"))
    sl.add_argument("name", nargs="?", help="slug name (for add/rm)")
    sl.set_defaults(fn=cmd_slug)

    args = p.parse_args(argv)
    args.fn(args)


if __name__ == "__main__":
    main()
