"""wl: SQLite-backed work log. work_log.md is a generated export; the DB is queried."""
import argparse
import os
import re
import signal
import sqlite3
import sys
import tempfile
from collections import Counter
from datetime import date, datetime
from pathlib import Path
from typing import NamedTuple

TYPES = ("ticket", "pr", "idea", "decision", "blocker", "note")
WEEKDAYS = ("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")  # date.weekday() order
# Project slugs are managed at runtime (`wl slug add/rm/ls`) and stored in the DB,
# not in this file. `known_slugs(conn)` returns them in display order.


class Entry(NamedTuple):
    ts: str    # ISO local 'YYYY-MM-DDTHH:MM:SS'; day = ts[:10]
    slug: str
    type: str
    refs: str  # comma-joined keys, '' if none
    body: str


_HHMM = re.compile(r"\d{2}:\d{2}")
_ISO_MIN = re.compile(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}")


def resolve_at(at, now=None):
    """None -> now; 'HH:MM' -> today at that time; 'YYYY-MM-DDTHH:MM' -> exact. Else ValueError.

    The regex checks the 2-digit shape; strptime then rejects impossible values
    (99:99, hour 24, month 13, ...) so garbage never reaches the timestamp column.
    """
    if now is None:
        now = datetime.now()
    if at is None:
        return now.strftime("%Y-%m-%dT%H:%M:%S")
    try:
        if _HHMM.fullmatch(at):
            datetime.strptime(at, "%H:%M")
            return now.strftime("%Y-%m-%d") + f"T{at}:00"
        if _ISO_MIN.fullmatch(at):
            datetime.strptime(at, "%Y-%m-%dT%H:%M")
            return at + ":00"
    except ValueError:
        pass  # shape matched but the value is impossible; fall through to one error
    raise ValueError(f"bad --at {at!r}; want HH:MM or YYYY-MM-DDTHH:MM")


def normalize_refs(s):
    """'PROJ-1, PROJ-2' -> 'PROJ-1,PROJ-2'; empty/None -> ''."""
    if not s:
        return ""
    return ",".join(p.strip() for p in s.split(",") if p.strip())


def check_slug(name):
    """Exit unless the slug survives a render/parse cycle: '### name', read back as \\S+.

    A slug with whitespace renders a heading the parser cannot see, and since the
    importer clears the table first, every entry under it disappears on the next
    command rather than at some later point a reader might notice.
    """
    if not re.fullmatch(r"\S+", name):
        sys.exit(f"error: slug {name!r} must be one word with no whitespace, "
                 "or entries under it are dropped when work_log.md is re-imported")


def check_refs(refs):
    """Exit on parens in refs: they close the '(refs: ...)' suffix early on re-import."""
    if set("()") & set(refs):
        sys.exit(f"error: refs {refs!r} may not contain parentheses")


def fmt_refs(refs):
    """Stored 'PROJ-1,PROJ-2' -> display 'PROJ-1, PROJ-2'; '' -> 'none'."""
    return refs.replace(",", ", ") if refs else "none"


_DAY_RE = re.compile(r"^## (\d{4}-\d{2}-\d{2})\s*$")
_SLUG_RE = re.compile(r"^### (\S+)\s*$")
# body is non-greedy so the optional trailing refs suffix is not swallowed. The refs
# group cannot span a paren, so it takes the LAST "(refs: ...)" on the line and a body
# that itself ends in "(refs: FM-1)" keeps it. It used to take the first, which ate the
# tail of the 2026-06-22 17:18 entry in the real log and left it holding
# refs = "FM-4357) (refs: FM-4359"; the next import of that line now repairs it.
_ENTRY_RE = re.compile(r"^- (\d{2}:\d{2}) \[(\w+)\] (.*?)(?:\s*\(refs:\s*([^()]*)\))?\s*$")


def parse_markdown(text):
    """Parse a rendered work_log.md back into Entry rows. Header and pre-day lines ignored."""
    entries, day, slug = [], None, None
    for line in text.splitlines():
        m = _DAY_RE.match(line)
        if m:
            day, slug = m.group(1), None
            continue
        m = _SLUG_RE.match(line)
        if m:
            slug = m.group(1)
            continue
        m = _ENTRY_RE.match(line)
        if m and day and slug:
            hhmm, typ, body, refs = m.groups()
            refs = "" if not refs or refs.strip().lower() == "none" else normalize_refs(refs)
            entries.append(Entry(f"{day}T{hhmm}:00", slug, typ, refs, body.rstrip()))
    return entries


HEADER_BLOCK = (
    "# Work Log\n\n"
    "Generated by `wl` from work_log.db; newest day first. Add entries with `wl add`.\n"
    "A hand-edit is re-imported on the next command, so keep the line shape or it is dropped."
)


def slug_sort_key(slug, order):
    """Registered slugs in `order` first, then unregistered slugs alphabetically."""
    return (order.index(slug), "") if slug in order else (len(order), slug)


def render_day(day, entries, order):
    """One '## day' section: slug groups in display order, entries time-sorted. No file header."""
    lines = [f"## {day}", ""]
    for slug in sorted({e.slug for e in entries}, key=lambda s: slug_sort_key(s, order)):
        lines.append(f"### {slug}")
        for e in sorted((x for x in entries if x.slug == slug), key=lambda x: x.ts):
            lines.append(f"- {e.ts[11:16]} [{e.type}] {e.body} (refs: {fmt_refs(e.refs)})")
        lines.append("")  # blank line after each slug block
    return "\n".join(lines).rstrip()


def render_days(entries, order):
    """Group entries by day and render each as a '## day' section, newest day first."""
    by_day = {}
    for e in entries:
        by_day.setdefault(e.ts[:10], []).append(e)
    return "\n\n".join(render_day(d, by_day[d], order) for d in sorted(by_day, reverse=True))


def render_markdown(entries, order):
    """Full work_log.md: header + every day newest-first + trailing newline."""
    body = render_days(entries, order)
    return f"{HEADER_BLOCK}\n\n{body}\n" if body else f"{HEADER_BLOCK}\n"


SCHEMA_VERSION = 1  # bump by one for every script appended to _MIGRATIONS

# Index 0 takes a database from version 0 to 1, index 1 from 1 to 2, and so on. Each
# script must be safe to run against a database that already has the shape it creates,
# because a pre-migration DB is adopted by stamping rather than rebuilding.
#
# This is deliberately not an ORM: one table, one two-column lookup table, no
# relationship between them, and no query anywhere that filters or sorts in SQL. A
# numbered list of statements is smaller than a model layer. Revisit when a second
# entity with a real relationship appears.
_MIGRATIONS = (
    """
    CREATE TABLE IF NOT EXISTS entries(
      id   INTEGER PRIMARY KEY,
      ts   TEXT NOT NULL,
      slug TEXT NOT NULL,
      type TEXT NOT NULL,
      refs TEXT NOT NULL DEFAULT '',
      body TEXT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_entries_ts ON entries(ts);
    CREATE TABLE IF NOT EXISTS slugs(
      name TEXT PRIMARY KEY,
      pos  INTEGER NOT NULL   -- display order, ascending
    );
    """,
)


def migrate(conn):
    """Bring the database up to SCHEMA_VERSION, then stamp it.

    Refusing a newer schema matters more than it looks: the database is the only copy of
    the data now, so an older build writing against a shape it does not understand is
    how rows get silently dropped.
    """
    have = conn.execute("PRAGMA user_version").fetchone()[0]
    if have > SCHEMA_VERSION:
        sys.exit(f"error: {db_path()} was written by a newer wl (schema {have}; this "
                 f"build knows {SCHEMA_VERSION}). Upgrade wl rather than downgrading the log.")
    for script in _MIGRATIONS[have:SCHEMA_VERSION]:
        conn.executescript(script)
    if have < SCHEMA_VERSION:
        # PRAGMA will not take a bound parameter, and SCHEMA_VERSION is our own int.
        conn.execute(f"PRAGMA user_version = {SCHEMA_VERSION}")
    conn.commit()


# ponytail: the pre-0.5 default was the tool's own parent directory. Kept only to warn
# people off it; delete this constant and warn_if_legacy_log_ignored() once nobody is
# running a pre-0.5 layout. Note the package split changes what this expression means.
_LEGACY_ROOT = Path(__file__).resolve().parent.parent


def data_dir():
    """Where the log lives when WORKLOG_ROOT is unset.

    XDG rather than beside the tool: once `wl` is installed from a package the old
    expression resolves into site-packages, and it silently relocated the log whenever
    the source layout changed, which is a data-loss shape rather than an inconvenience.
    """
    xdg = os.environ.get("XDG_DATA_HOME")
    return Path(xdg) / "worklog" if xdg else Path.home() / ".local" / "share" / "worklog"


def root():
    env = os.environ.get("WORKLOG_ROOT")
    return Path(env) if env else data_dir()


def ensure_root():
    """The root may not exist yet: the XDG default usually does not on a first run."""
    r = root()
    r.mkdir(parents=True, exist_ok=True)
    return r


def warn_if_legacy_log_ignored(legacy_root=None):
    """Point at a pre-0.5 log this install would otherwise ignore, and keep going.

    Non-fatal on purpose: a genuine first run has no legacy log and must not be blocked,
    and moving somebody's only copy of their data unasked is worse than telling them
    where it is.
    """
    if os.environ.get("WORKLOG_ROOT") or db_path().exists():
        return
    legacy = (legacy_root or _LEGACY_ROOT) / "work_log.db"
    if legacy.exists():
        print(f"warning: {legacy} holds a log this install ignores. "
              f"Set WORKLOG_ROOT={legacy.parent} to keep using it, "
              f"or move it to {root()}.", file=sys.stderr)


def md_path():
    return root() / "work_log.md"


def db_path():
    return root() / "work_log.db"


def _import_into(conn):
    """Rebuild the entries table from work_log.md (source of record)."""
    conn.execute("DELETE FROM entries")
    md = md_path()
    if md.exists():
        rows = [(e.ts, e.slug, e.type, e.refs, e.body) for e in parse_markdown(md.read_text())]
        conn.executemany(
            "INSERT INTO entries(ts,slug,type,refs,body) VALUES(?,?,?,?,?)", rows
        )
    conn.commit()


def connect():
    """Open the DB, ensure schema, and re-import the markdown if it is newer (or DB missing)."""
    ensure_root()
    db = db_path()
    stale = (not db.exists()) or (
        md_path().exists() and md_path().stat().st_mtime > db.stat().st_mtime
    )
    conn = sqlite3.connect(str(db))
    conn.execute("PRAGMA busy_timeout = 5000")
    migrate(conn)
    # ponytail: slugs live in the DB, not work_log.md, so they are machine-local
    # tooling config, not portable log content. A from-scratch `wl import` reseeds
    # to just 'general'. Add a slug export to the markdown only if that ever bites.
    if not conn.execute("SELECT 1 FROM slugs LIMIT 1").fetchone():
        conn.execute("INSERT INTO slugs(name, pos) VALUES('general', 0)")
        conn.commit()
    if stale:
        _import_into(conn)
    return conn


def _all_entries(conn):
    rows = conn.execute("SELECT ts,slug,type,refs,body FROM entries").fetchall()
    return [Entry(*r) for r in rows]


def known_slugs(conn):
    """Registered slug names in display (pos) order."""
    return [r[0] for r in conn.execute("SELECT name FROM slugs ORDER BY pos")]


def _roundtrip_key(e):
    """Entry identity for comparison, minus the seconds the markdown does not render."""
    return (e.ts[:16], e.slug, e.type, e.refs, e.body)


def write_md(conn):
    """Render all entries and atomically replace work_log.md, if it reads back intact.

    work_log.md is the source of record and every command re-imports it once it is
    newer than the DB, so anything the renderer writes that parse_markdown cannot read
    back is permanent loss, and silent. Cheaper to verify the round trip here than to
    guess at every character that might break it.
    """
    entries = _all_entries(conn)
    text = render_markdown(entries, known_slugs(conn))
    survived = set(map(_roundtrip_key, parse_markdown(text)))
    lost = sorted(k for k in map(_roundtrip_key, entries) if k not in survived)
    if lost:
        listing = "\n".join(f"  {ts} [{slug}] [{typ}] {body[:60]}"
                            for ts, slug, typ, _, body in lost)
        sys.exit(f"error: work_log.md not replaced; {len(lost)} entr"
                 f"{'y' if len(lost) == 1 else 'ies'} would not survive re-import:\n{listing}\n"
                 "The DB now disagrees with the file; `wl import` resyncs from the file.")
    target = md_path()
    fd, tmp = tempfile.mkstemp(dir=str(target.parent), suffix=".tmp")
    with os.fdopen(fd, "w") as f:
        f.write(text)
    os.replace(tmp, str(target))


def cmd_add(args):
    if args.type not in TYPES:
        sys.exit(f"error: bad --type {args.type!r}; valid: {', '.join(TYPES)}")
    try:
        ts = resolve_at(args.at)
    except ValueError as e:
        sys.exit(f"error: {e}")
    check_slug(args.slug)
    refs = normalize_refs(args.ref)
    check_refs(refs)
    body = args.body.replace("\n", " ").strip()
    conn = connect()
    if args.slug not in known_slugs(conn):
        print(f"warning: unknown slug {args.slug!r} "
              f"(register it with `wl slug add {args.slug}`?)", file=sys.stderr)
    conn.execute(
        "INSERT INTO entries(ts,slug,type,refs,body) VALUES(?,?,?,?,?)",
        (ts, args.slug, args.type, refs, body),
    )
    conn.commit()
    write_md(conn)
    conn.close()
    print(f"- {ts[11:16]} [{args.type}] {body} (refs: {fmt_refs(refs)})")


def cmd_report(args):
    conn = connect()
    order = known_slugs(conn)
    entries = _all_entries(conn)
    conn.close()
    # Range mode (--since/--until) takes precedence over --day, so a roundup for a
    # standup or bi-weekly meeting is one command. Date strings are YYYY-MM-DD, which
    # compares correctly as plain strings; open-ended bounds use lexical sentinels.
    if args.since or args.until:
        lo, hi = args.since or "0000-00-00", args.until or "9999-99-99"
        sel = [e for e in entries if lo <= e.ts[:10] <= hi]
        label = f"{lo}..{hi}"
    else:
        day = datetime.now().strftime("%Y-%m-%d") if args.day == "today" else args.day
        sel = [e for e in entries if e.ts[:10] == day]
        label = day
    if not sel:
        print(f"(no entries for {label})")
        return
    print(render_days(sel, order))


def ref_matches(ref, e):
    """True if `ref` is in the refs column, or named as a whole key in the body.

    Whole keys in both places, so PROJ-1 never matches PROJ-10. The body is searched
    because entries routinely name a ticket in prose without filling --ref, and those
    mentions were unreachable by `wl log --ref`.
    """
    return ref in e.refs.split(",") or re.search(rf"\b{re.escape(ref)}\b", e.body) is not None


def matches(e, args):
    """Shared --slug/--type/--ref/--since/--until filter for `log` and `stats`.

    Phrased as "keep unless some filter excludes it" so an unset filter is simply
    falsy and drops out, rather than needing a branch of its own.
    """
    return not (
        (args.slug and e.slug != args.slug)
        or (args.type and e.type != args.type)
        or (args.ref and not ref_matches(args.ref, e))
        or (args.since and e.ts[:10] < args.since)
        or (args.until and e.ts[:10] > args.until)
    )


def cmd_log(args):
    conn = connect()
    entries = _all_entries(conn)
    conn.close()
    hits = sorted((e for e in entries if matches(e, args)), key=lambda x: x.ts, reverse=True)
    # Output is newest-first, so a limit keeps the newest. Limited by default because
    # the usual reader is a script or an agent with a context window, and an unfiltered
    # `wl log` is the entire history in one write. Never a silent cap: the tail line
    # says what was withheld.
    shown = hits[:args.limit] if args.limit > 0 else hits
    for e in shown:
        print(f"{e.ts[:10]} {e.ts[11:16]} [{e.slug}] [{e.type}] "
              f"{e.body} (refs: {fmt_refs(e.refs)})")
    if len(hits) > len(shown):
        print(f"... and {len(hits) - len(shown)} more (--limit 0 for all)")


def iso_week(day):
    """'YYYY-MM-DD' -> 'YYYY-Www' ISO week label, e.g. '2026-W33'.

    ISO weeks, not strftime %W, because the team counts weeks that way everywhere
    else (brag doc, sprint names), and the two disagree around New Year.
    """
    y, w, _ = date.fromisoformat(day).isocalendar()
    return f"{y}-W{w:02d}"


def _counts(values):
    """Descending (value, count) pairs. Ties break on name so output is stable."""
    return sorted(Counter(values).items(), key=lambda kv: (-kv[1], kv[0]))


def _bar(n, mx, width=24):
    """Proportional bar, scaled to the largest row. A non-zero count always gets at
    least one block, so a small-but-present value never renders as absent."""
    return "█" * max(1, round(n / mx * width)) if n else ""


def _print_block(title, pairs, limit=None):
    """One aligned 'name count bar' block, in the order given. Silent when empty.

    Rows are never re-sorted here: chronological blocks (week, weekday, hour) rely
    on the caller's order, and sorting by size would hide the gaps that matter.
    """
    if not pairs:
        return
    rows = pairs[:limit] if limit else pairs
    width = max(len(k) for k, _ in rows)
    nwidth = max(len(str(n)) for _, n in rows)
    mx = max(n for _, n in rows)
    print(f"\n{title}")
    for name, n in rows:
        print(f"  {name:<{width}}  {n:>{nwidth}}  {_bar(n, mx)}")
    if limit and len(pairs) > limit:
        print(f"  ... and {len(pairs) - limit} more")


def cmd_stats(args):
    conn = connect()
    entries = _all_entries(conn)
    conn.close()
    sel = [e for e in entries if matches(e, args)]
    if not sel:
        print("(no entries)")
        return
    days = sorted(e.ts[:10] for e in sel)
    print(f"{len(sel)} entries, {days[0]} to {days[-1]}")
    _print_block("by type", _counts(e.type for e in sel))
    _print_block("by slug", _counts(e.slug for e in sel))
    # Weeks sort chronologically rather than by size: the shape of the run over time
    # is the point, and a busiest-first list hides gaps.
    _print_block("by week", sorted(Counter(iso_week(e.ts[:10]) for e in sel).items()))
    # One entry can cite several tickets, so refs are counted per mention, not per entry.
    refs = [r for e in sel for r in e.refs.split(",") if r]
    _print_block(f"top refs (of {len(set(refs))})", _counts(refs), limit=args.top)
    if getattr(args, "when", False):
        # Both blocks read in clock order, not by size: the question is when the work
        # happens, so an empty Friday or a busy midnight has to sit where it falls.
        dow = Counter(date.fromisoformat(e.ts[:10]).weekday() for e in sel)
        _print_block("by weekday", [(WEEKDAYS[i], dow[i]) for i in range(7) if dow[i]])
        # Hours are only listed when used, so a normal day is ~10 rows rather than 24.
        _print_block("by hour", sorted(Counter(e.ts[11:13] for e in sel).items()))


def cmd_render(args):
    conn = connect()
    write_md(conn)
    conn.close()
    print(f"rendered {md_path()}")


def cmd_import(args):
    conn = connect()
    _import_into(conn)  # force a rebuild even if connect() considered the DB fresh
    n = conn.execute("SELECT count(*) FROM entries").fetchone()[0]
    conn.close()
    print(f"imported {md_path()} -> {db_path()} ({n} entries)")


def cmd_slug(args):
    conn = connect()
    if args.action == "ls":
        for name in known_slugs(conn):
            print(name)
    elif args.action == "add":
        if not args.name:
            conn.close()
            sys.exit("error: `slug add` needs a name")
        check_slug(args.name)
        # pos = one past the current max, so new slugs append to the display order.
        cur = conn.execute(
            "INSERT OR IGNORE INTO slugs(name, pos) "
            "VALUES(?, (SELECT COALESCE(MAX(pos), -1) + 1 FROM slugs))",
            (args.name,),
        )
        conn.commit()
        print(f"added slug {args.name!r}" if cur.rowcount
              else f"slug {args.name!r} already registered")
    elif args.action == "rm":
        if not args.name:
            conn.close()
            sys.exit("error: `slug rm` needs a name")
        cur = conn.execute("DELETE FROM slugs WHERE name = ?", (args.name,))
        conn.commit()
        if not cur.rowcount:
            print(f"slug {args.name!r} was not registered")
        else:
            n = conn.execute("SELECT count(*) FROM entries WHERE slug = ?",
                             (args.name,)).fetchone()[0]
            note = f" ({n} existing entries will now sort as unknown)" if n else ""
            print(f"removed slug {args.name!r}{note}")
    conn.close()


def main(argv=None):
    warn_if_legacy_log_ignored()
    # `wl log | head` is a normal thing to type: die on SIGPIPE the way any other
    # CLI does, rather than printing a BrokenPipeError traceback over the output.
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)
    p = argparse.ArgumentParser(prog="wl", description="SQLite-backed work log.")
    sub = p.add_subparsers(dest="cmd", required=True)

    a = sub.add_parser("add", help="add an entry and re-render work_log.md")
    a.add_argument("--slug", required=True)
    a.add_argument("--type", required=True)
    a.add_argument("--ref", default="")
    a.add_argument("--at", help="HH:MM (today) or YYYY-MM-DDTHH:MM; default now")
    a.add_argument("body")
    a.set_defaults(fn=cmd_add)

    r = sub.add_parser("report", help="print one day (or a --since/--until range) as markdown")
    r.add_argument("--day", default="today")
    r.add_argument("--since", help="range start YYYY-MM-DD; groups every day in range")
    r.add_argument("--until", help="range end YYYY-MM-DD, inclusive")
    r.set_defaults(fn=cmd_report)

    def add_filter_args(sp):
        """The --slug/--type/--ref/--since/--until set, shared by `log` and `stats`."""
        sp.add_argument("--slug")
        sp.add_argument("--type")
        sp.add_argument("--ref")
        sp.add_argument("--since")
        sp.add_argument("--until")

    g = sub.add_parser("log", help="filtered list across all history, newest first")
    add_filter_args(g)
    g.add_argument("-n", "--limit", type=int, default=20,
                   help="show only the newest N; 0 for all (default 20)")
    g.set_defaults(fn=cmd_log)

    st = sub.add_parser("stats", help="counts by type, slug, ISO week and ticket")
    add_filter_args(st)
    st.add_argument("--top", type=int, default=10, help="how many refs to list; default 10")
    st.add_argument("--when", action="store_true",
                    help="also break down by weekday and hour of day")
    st.set_defaults(fn=cmd_stats)

    rn = sub.add_parser("render", help="regenerate work_log.md from the DB")
    rn.set_defaults(fn=cmd_render)

    im = sub.add_parser("import", help="rebuild the DB from work_log.md")
    im.set_defaults(fn=cmd_import)

    sl = sub.add_parser("slug", help="manage project slugs (ls/add/rm)")
    sl.add_argument("action", choices=("ls", "add", "rm"))
    sl.add_argument("name", nargs="?", help="slug name (for add/rm)")
    sl.set_defaults(fn=cmd_slug)

    args = p.parse_args(argv)
    args.fn(args)


if __name__ == "__main__":
    main()
