#!/usr/bin/env python3
"""wl: SQLite-backed work log. work_log.md is a generated export; the DB is queried."""
import argparse
import os
import re
import sqlite3
import sys
import tempfile
from datetime import datetime
from pathlib import Path
from typing import NamedTuple

TYPES = ("ticket", "pr", "idea", "decision", "blocker", "note")
SLUG_ORDER = ("general",)  # canonical slugs sort first; add your own project slugs here


class Entry(NamedTuple):
    ts: str    # ISO local 'YYYY-MM-DDTHH:MM:SS'; day = ts[:10]
    slug: str
    type: str
    refs: str  # comma-joined keys, '' if none
    body: str


_HHMM = re.compile(r"\d{2}:\d{2}")
_ISO_MIN = re.compile(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}")


def resolve_at(at, now=None):
    """None -> now; 'HH:MM' -> today at that time; 'YYYY-MM-DDTHH:MM' -> exact. Else ValueError."""
    if now is None:
        now = datetime.now()
    if at is None:
        return now.strftime("%Y-%m-%dT%H:%M:%S")
    if _HHMM.fullmatch(at):
        return now.strftime("%Y-%m-%d") + f"T{at}:00"
    if _ISO_MIN.fullmatch(at):
        return at + ":00"
    raise ValueError(f"bad --at {at!r}; want HH:MM or YYYY-MM-DDTHH:MM")


def normalize_refs(s):
    """'PROJ-1, PROJ-2' -> 'PROJ-1,PROJ-2'; empty/None -> ''."""
    if not s:
        return ""
    return ",".join(p.strip() for p in s.split(",") if p.strip())


_DAY_RE = re.compile(r"^## (\d{4}-\d{2}-\d{2})\s*$")
_SLUG_RE = re.compile(r"^### (\S+)\s*$")
# body is non-greedy so the optional trailing refs suffix is not swallowed.
# ponytail: a body literally ending in "(refs: ...)" would mis-parse; no real entry does this.
_ENTRY_RE = re.compile(r"^- (\d{2}:\d{2}) \[(\w+)\] (.*?)(?:\s*\(refs:\s*(.*?)\))?\s*$")


def parse_markdown(text):
    """Parse a rendered work_log.md back into Entry rows. Header and pre-day lines ignored."""
    entries, day, slug = [], None, None
    for line in text.splitlines():
        m = _DAY_RE.match(line)
        if m:
            day, slug = m.group(1), None
            continue
        m = _SLUG_RE.match(line)
        if m:
            slug = m.group(1)
            continue
        m = _ENTRY_RE.match(line)
        if m and day and slug:
            hhmm, typ, body, refs = m.groups()
            refs = "" if not refs or refs.strip().lower() == "none" else normalize_refs(refs)
            entries.append(Entry(f"{day}T{hhmm}:00", slug, typ, refs, body.rstrip()))
    return entries


HEADER_BLOCK = (
    "# Work Log\n\n"
    "Generated by `wl` from work_log.db. Do not hand-edit; use `wl add`. Newest day first."
)


def slug_sort_key(slug):
    """Canonical slugs in SLUG_ORDER first, then unknown slugs alphabetically."""
    return (SLUG_ORDER.index(slug), "") if slug in SLUG_ORDER else (len(SLUG_ORDER), slug)


def render_day(day, entries):
    """One '## day' section: slug groups in display order, entries time-sorted. No file header."""
    lines = [f"## {day}", ""]
    for slug in sorted({e.slug for e in entries}, key=slug_sort_key):
        lines.append(f"### {slug}")
        for e in sorted((x for x in entries if x.slug == slug), key=lambda x: x.ts):
            refs = e.refs.replace(",", ", ") if e.refs else "none"
            lines.append(f"- {e.ts[11:16]} [{e.type}] {e.body} (refs: {refs})")
        lines.append("")  # blank line after each slug block
    return "\n".join(lines).rstrip()


def render_markdown(entries):
    """Full work_log.md: header + every day newest-first + trailing newline."""
    by_day = {}
    for e in entries:
        by_day.setdefault(e.ts[:10], []).append(e)
    blocks = [render_day(d, by_day[d]) for d in sorted(by_day, reverse=True)]
    body = "\n\n".join(blocks)
    return f"{HEADER_BLOCK}\n\n{body}\n" if body else f"{HEADER_BLOCK}\n"


_SCHEMA = """
CREATE TABLE IF NOT EXISTS entries(
  id   INTEGER PRIMARY KEY,
  ts   TEXT NOT NULL,
  slug TEXT NOT NULL,
  type TEXT NOT NULL,
  refs TEXT NOT NULL DEFAULT '',
  body TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_entries_ts ON entries(ts);
"""


def root():
    env = os.environ.get("WORKLOG_ROOT")
    return Path(env) if env else Path(__file__).resolve().parent.parent


def md_path():
    return root() / "work_log.md"


def db_path():
    return root() / "work_log.db"


def _import_into(conn):
    """Rebuild the entries table from work_log.md (source of record)."""
    conn.execute("DELETE FROM entries")
    md = md_path()
    if md.exists():
        rows = [(e.ts, e.slug, e.type, e.refs, e.body) for e in parse_markdown(md.read_text())]
        conn.executemany(
            "INSERT INTO entries(ts,slug,type,refs,body) VALUES(?,?,?,?,?)", rows
        )
    conn.commit()


def connect():
    """Open the DB, ensure schema, and re-import the markdown if it is newer (or DB missing)."""
    db = db_path()
    stale = (not db.exists()) or (
        md_path().exists() and md_path().stat().st_mtime > db.stat().st_mtime
    )
    conn = sqlite3.connect(str(db))
    conn.execute("PRAGMA busy_timeout = 5000")
    conn.executescript(_SCHEMA)
    if stale:
        _import_into(conn)
    return conn


def _all_entries(conn):
    rows = conn.execute("SELECT ts,slug,type,refs,body FROM entries").fetchall()
    return [Entry(*r) for r in rows]


def write_md(conn):
    """Render all entries and atomically replace work_log.md."""
    text = render_markdown(_all_entries(conn))
    target = md_path()
    fd, tmp = tempfile.mkstemp(dir=str(target.parent), suffix=".tmp")
    with os.fdopen(fd, "w") as f:
        f.write(text)
    os.replace(tmp, str(target))


def cmd_add(args):
    if args.type not in TYPES:
        sys.exit(f"error: bad --type {args.type!r}; valid: {', '.join(TYPES)}")
    if args.slug not in SLUG_ORDER:
        print(f"warning: unknown slug {args.slug!r} (new project?)", file=sys.stderr)
    try:
        ts = resolve_at(args.at)
    except ValueError as e:
        sys.exit(f"error: {e}")
    refs = normalize_refs(args.ref)
    body = args.body.replace("\n", " ").strip()
    conn = connect()
    conn.execute(
        "INSERT INTO entries(ts,slug,type,refs,body) VALUES(?,?,?,?,?)",
        (ts, args.slug, args.type, refs, body),
    )
    conn.commit()
    write_md(conn)
    conn.close()
    refs_disp = refs.replace(",", ", ") if refs else "none"
    print(f"- {ts[11:16]} [{args.type}] {body} (refs: {refs_disp})")


def cmd_report(args):
    conn = connect()
    day = datetime.now().strftime("%Y-%m-%d") if args.day == "today" else args.day
    entries = [e for e in _all_entries(conn) if e.ts[:10] == day]
    conn.close()
    if not entries:
        print(f"(no entries for {day})")
        return
    print(render_day(day, entries))


def cmd_log(args):
    conn = connect()
    entries = _all_entries(conn)
    conn.close()

    def keep(e):
        if args.slug and e.slug != args.slug:
            return False
        if args.type and e.type != args.type:
            return False
        if args.ref and args.ref not in e.refs.split(","):
            return False
        if args.since and e.ts[:10] < args.since:
            return False
        if args.until and e.ts[:10] > args.until:
            return False
        return True

    hits = sorted((e for e in entries if keep(e)), key=lambda x: x.ts, reverse=True)
    for e in hits:
        refs = e.refs.replace(",", ", ") if e.refs else "none"
        print(f"{e.ts[:10]} {e.ts[11:16]} [{e.slug}] [{e.type}] {e.body} (refs: {refs})")


def cmd_render(args):
    conn = connect()
    write_md(conn)
    conn.close()
    print(f"rendered {md_path()}")


def cmd_import(args):
    conn = connect()
    _import_into(conn)  # force a rebuild even if connect() considered the DB fresh
    n = conn.execute("SELECT count(*) FROM entries").fetchone()[0]
    conn.close()
    print(f"imported {md_path()} -> {db_path()} ({n} entries)")


def main(argv=None):
    p = argparse.ArgumentParser(prog="wl", description="SQLite-backed work log.")
    sub = p.add_subparsers(dest="cmd", required=True)

    a = sub.add_parser("add", help="add an entry and re-render work_log.md")
    a.add_argument("--slug", required=True)
    a.add_argument("--type", required=True)
    a.add_argument("--ref", default="")
    a.add_argument("--at", help="HH:MM (today) or YYYY-MM-DDTHH:MM; default now")
    a.add_argument("body")
    a.set_defaults(fn=cmd_add)

    r = sub.add_parser("report", help="print one day as markdown")
    r.add_argument("--day", default="today")
    r.set_defaults(fn=cmd_report)

    g = sub.add_parser("log", help="filtered list across all history")
    g.add_argument("--slug")
    g.add_argument("--type")
    g.add_argument("--ref")
    g.add_argument("--since")
    g.add_argument("--until")
    g.set_defaults(fn=cmd_log)

    rn = sub.add_parser("render", help="regenerate work_log.md from the DB")
    rn.set_defaults(fn=cmd_render)

    im = sub.add_parser("import", help="rebuild the DB from work_log.md")
    im.set_defaults(fn=cmd_import)

    args = p.parse_args(argv)
    args.fn(args)


if __name__ == "__main__":
    main()
